const siteContent = {
  brandName: "SLUX PERFUME",
  home: "Home",
  collection: "Collection",
  showcase: "Showcase",
  testimonials: "Testimonials",
  contact: "Contact",
  search: "search",
  cart: "shopping_cart",
  person: "person",
  intro: "Luxury in Every Spritz.",
  introContent:
    "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta, saepe. Quisquam officiis numquam blanditiis alias, nab maiores consequuntur natus, minus doloremque architecto a corporis cupiditate minima nulla autem possimus?",
  buy: "Shop now!",
  view: "View products",
  Previous: "Previous",
  Next: "Next",
  chanel: "Chanel",
  ch1price: "$172",
  ch1name: "Cristalle Eau Verte",
  ch1desc: "Eau De Parfum Spray",
  add: "ADD TO CART",
  ch2price: "$110",
  ch2name: "Coco mademoiselle",
  ch2desc: "Eau De Parfum Intense Spray",
  ch3price: "$130",
  ch3name: "ÉGOÏSTE",
  ch3desc: "Eau de Toilette Spray",
  ch4price: "$160",
  ch4name: "bleu de chanel",
  ch4desc: "Parfum Spray",
  bvlgari: "bvlgari",
  b1price: "$280",
  b1name: "allegra",
  b1desc: "Fiori D’amore Eau De Parfum",
  b2price: "$160",
  b2name: "omnia",
  b2desc: "Crystalline Eau De Parfum",
  b3price: "$460",
  b3name: "Le Gemme Tygar",
  b3desc: "Eau De Parfum",
  b4price: "$148",
  b4name: "Man Glacial Essence",
  b4desc: "Eau De Parfum",
  dior: "dior",
  d1price: "$172",
  d1name: "miss dior",
  d1desc: "Dior youth and femininity",
  d2price: "$177",
  d2name: "J'adore l'Or",
  d2desc: "Beauty of the J'adore flowers",
  d3price: "$160",
  d3name: "sauvage",
  d3desc: "Eau Forte Parfum",
  d4price: "$130",
  d4name: "fahrenheit",
  d4desc: "Eau De Toilette",
  gucci: "gucci",
  g1price: "$138",
  g1name: "bloom",
  g1desc: "Eau De Toilette",
  g2price: "$168",
  g2name: "flora",
  g2desc: "Eau De Parfum",
  g3price: "$183",
  g3name: "guilty elixir",
  g3desc: "Parfum Pour Homme",
  g4price: "$120",
  g4name: "guilty essence",
  g4desc: "Eau De Toilette",
  dolce: "dolce",
  and: "&",
  gabbana: "gabbana",
  dg1price: "$140",
  dg1name: "The Only One",
  dg1desc: "Eau De Parfum",
  dg2price: "$175",
  dg2name: "devotion",
  dg2desc: "Eau De Parfum",
  dg3price: "$162",
  dg3name: "k by d&g",
  dg3desc: "Eau De Parfum Intense",
  dg4price: "$149",
  dg4name: "The One for Men",
  dg4desc: "Eau De Toilette",
  v: "v",
  title: "ictoria's",
  s: "s",
  title1: "ecret",
  vsprice: "$159",
  vs1name: "Bare",
  vs1desc: "Eau De Parfum",
  vs2name: "bombshell intense",
  vs2desc: "Eau De Parfum",
  vs3name: "Tease Crème Cloud",
  vs3desc: "Eau De Parfum",
  vs4name: "VS HIM",
  vs4desc: "Platinum Fragrance",
  highlight1: "Legit Shop!!",
  lorem:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae sunt quos quas placeat et, nobis pariatur exnecessitatibus ullam accusamus deserunt molestias veniam reprehenderit, cum unde sint illum culpa voluptatum!",
  rate: "star_rate",
  halfrate: "star_rate_half",
  testimony1: "Ciedrick Ramos",
  Description: "Loyal Customer",
  highlight2: "Exceptional Service!",
  testimony2: "Drose Certeza",
  highlight3: "A statement of elegance!",
  testimony3: "Mark Calendario",
  highlight4: "Top-notch Experience!",
  testimony4: "Richter Villas",
  highlight5: "Stunning products!",
  testimony5: "Nicole Marcellana",
  highlight6: "Quality at its finest ~",
  testimony6: "Darylle Villanueva",
  contactTitle: "Contact Us",
  Send: "Send",
  fbInfo: "sluxperfume.ph",
  xInfo: "@slux.perfume",
  igInfo: "@sluxperfume_ph",
  slux: " © SLUX PERFUME 2024 ",
  end: "All rights reserved.",
};

function showsite() {
  const template = document.getElementById("template").innerHTML;
  const rendered = Mustache.render(template, siteContent);
  document.getElementById("target").innerHTML = rendered;
}
